name: Build PDF

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-pdf.yml

  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a pull request
        required: false
        default: "false"
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-pdf:
    permissions:
      contents: write
      pull-requests: write
    name: Build PDF
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.repository_owner == 'luxass' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.0.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build PDF
        uses: tj-actions/docker-run@v2
        id: build-pdf
        with:
          image: ghcr.io/puppeteer/puppeteer:21.5.2
          name: puppeteer-chrome
          options: "-i --init --cap-add=SYS_ADMIN -v ${{ github.workspace }}:${{ github.workspace }}"
          args: |
            bash -c '
            files=("package.json" "scripts/build-pdf.mjs" "node_modules")

            for file in "${files[@]}"; do
              echo "Copying $file..."

              # Set up the target directory in /home/pptruser/build-pdf
              target_dir="/home/pptruser/build-pdf"
              mkdir -p "$target_dir"

              # Specify the source and destination files
              source_file="${{ github.workspace }}/$file"
              destination_file="$target_dir/$(basename "$file")"

              # Copy the file to the target directory
              cp -r "$source_file" "$destination_file"

              echo "Copied $file to $destination_file"
            done

            # copy public to target dir
            cp -r "${{ github.workspace }}/public" "$target_dir"

            cd $target_dir

            npx puppeteer browsers install chrome

            # run npm install after copying files
            npm install --force

            # running the build-pdf
            node build-pdf.mjs
            '

      - name: Copy PDF
        uses: tj-actions/docker-cp@v2
        with:
          container: ${{ steps.build-pdf.outputs.container-id }}
          source: /home/pptruser/build-pdf/public/resume.pdf
          destination: ./public/resume.pdf

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        if: ${{ github.event.inputs.dry-run != 'true' }}
        with:
          commit-message: "feat: updated pdf file"
          title: "feat: updated pdf file"
          body: |
            This is an automated PR to update the PDF file.

            If you want to merge this PR, please review the changes and merge it manually.
          branch: update-pdf
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          assignees: luxass
          base: main
