name: Build PDF

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a pull request
        required: false
        default: "false"
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ROBOBUB_TOKEN }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install depdencies
        run: pnpm install



      - name: Build PDF
        uses: tj-actions/puppeteer@v5
        id: build-pdf
        with:
          files: |
            scripts/build-pdf.mjs

      - name: Copy PDF
        uses: tj-actions/docker-cp@v2
        with:
          container: ${{ steps.build-pdf.outputs.container-id }}
          source: ${{ steps.build-pdf.outputs.home }}/public/resume.pdf
          destination: ./public/resume.pdf

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: ${{ github.event.inputs.dry-run != 'true' }}
        with:
          commit-message: "feat: updated pdf file"
          title: "feat: updated pdf file"
          body: |
            This is an automated PR to update the PDF file.

            If you want to merge this PR, please review the changes and merge it manually.
          branch: update-pdf
          author: robobub <bot@luxass.dev>
          base: main
          reviewers: luxass
          token: ${{ secrets.ROBOBUB_TOKEN }}
