name: CI

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a pull request
        required: false
        default: "false"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install depdencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Typecheck
        run: pnpm typecheck

      # disabled until im publishing my new eslint config
      # - name: Lint
      #   run: pnpm lint
